import { AsyncLocalStorage } from 'node:async_hooks';
import { createServer } from 'node:http';
import process from 'node:process';

import { createApp } from '../../../backend/src/app.js';
import { ConversationRepository } from '../../../backend/src/infrastructure/postgres/repositories/conversationRepository.js';
import { ContextRepository } from '../../../backend/src/infrastructure/postgres/repositories/contextRepository.js';
import { TurnRepository } from '../../../backend/src/infrastructure/postgres/repositories/turnRepository.js';
import { ContextBuilder } from '../../../backend/src/services/conversations/ContextBuilder.js';
import { ConversationService } from '../../../backend/src/services/conversations/ConversationService.js';
import { TurnEventPublisher } from '../../../backend/src/services/conversations/turnEventPublisher.js';
import { TurnOrchestrator } from '../../../backend/src/services/conversations/TurnOrchestrator.js';
import { ModelCatalogService } from '../../../backend/src/services/llm/ModelCatalogService.js';
import {
  assertModelFuseSchema,
  createIntegrationPool,
} from '../../../backend/src/test/integration/testDatabase.js';
import type {
  CredentialEnvironmentVariable,
  DeploymentDefinition,
  ProviderId,
  ResponseSlot,
} from '../../../backend/src/types/conversations.js';
import type {
  LlmProvider,
  LlmProviderError,
  LlmRequest,
  LlmResult,
  ProviderRegistry,
} from '../../../backend/src/types/llm.js';
import {
  catalogScenarioProviders,
  E2E_FRONTEND_ORIGIN,
  fakeDeploymentCatalog,
  fakeModelScenarios,
  fakeResponseContent,
  type CatalogScenario,
} from './scenarios.js';

const PORT = 3001;
const HOST = '127.0.0.1';
const STARTED_AT = '2026-01-02T03:04:05.000Z';
const COMPLETED_AT = '2026-01-02T03:04:06.000Z';
const RUN_ID_PATTERN = /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const UUID_PATTERN = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const requestCatalogScenario = new AsyncLocalStorage<CatalogScenario>();

const runId = process.env.MODELFUSE_E2E_RUN_ID;
if (!runId || !RUN_ID_PATTERN.test(runId)) {
  throw new Error('MODELFUSE_E2E_RUN_ID must be a UUID generated by Playwright');
}

process.env.NODE_ENV = 'test';
process.env.FRONTEND_URL_LOCALHOST = E2E_FRONTEND_ORIGIN;

const credentialByProvider: Readonly<Record<ProviderId, CredentialEnvironmentVariable>> = {
  openai: 'OPENAI_API_KEY',
  google: 'GOOGLE_API_KEY',
  minimax: 'MINIMAX_API_KEY',
  qwen: 'QWEN_API_KEY',
  openrouter: 'OPENROUTER_API_KEY',
};

const deploymentDefinitions: readonly DeploymentDefinition[] = fakeDeploymentCatalog.map(
  deployment => ({
    ...deployment,
    credentialEnv: credentialByProvider[deployment.providerId],
  })
);

const continuationGates = new Map<
  string,
  { readonly promise: Promise<void>; readonly release: () => void }
>();

function continuationGate(prompt: string) {
  let gate = continuationGates.get(prompt);
  if (gate) return gate;

  let release = () => {};
  const promise = new Promise<void>(resolve => {
    release = resolve;
  });
  gate = { promise, release };
  continuationGates.set(prompt, gate);
  return gate;
}

class ScenarioLlmProvider implements LlmProvider {
  private readonly callsByPrompt = new Map<string, number>();

  constructor(readonly providerId: ProviderId) {}

  async measureInputTokens(
    deployment: LlmRequest['deployment'],
    messages: LlmRequest['messages']
  ): Promise<number> {
    if (!messages.some(message => message.content.includes(fakeModelScenarios.contextProtection.marker))) {
      return 1;
    }
    const contentLength = messages.reduce((total, message) => total + message.content.length, 0);
    return Math.ceil((contentLength * deployment.contextLimitTokens) / 400);
  }

  async generate(request: LlmRequest): Promise<LlmResult> {
    const prompt = request.messages.at(-1)?.content ?? '';

    if (prompt.includes(fakeModelScenarios.continuationBusy.marker)) {
      await continuationGate(prompt).promise;
    }

    if (request.slot === 'base-1' && prompt.includes(fakeModelScenarios.retry.marker)) {
      const attempt = (this.callsByPrompt.get(prompt) ?? 0) + 1;
      this.callsByPrompt.set(prompt, attempt);
      if (attempt === 1) throw this.timeoutFailure(request);
      return this.result(fakeModelScenarios.retry.recoveredBase1Content, request);
    }

    if (request.slot === 'base-1' && prompt.includes(fakeModelScenarios.continueWithout.marker)) {
      throw this.timeoutFailure(request);
    }

    if (request.slot === 'consolidator' && prompt.includes(fakeModelScenarios.retry.marker)) {
      const hasRecoveredBase1 = request.messages.some(message =>
        message.content.includes(`base-1:\n${fakeModelScenarios.retry.recoveredBase1Content}`)
      );
      return this.result(
        hasRecoveredBase1
          ? fakeModelScenarios.retry.reconsolidatedContent
          : fakeModelScenarios.retry.initialConsolidatorContent,
        request
      );
    }

    return this.result(
      fakeResponseContent(request.slot, request.deployment.deploymentId),
      request
    );
  }

  private result(content: string, request: LlmRequest): LlmResult {
    return {
      content,
      provider: request.deployment.providerId,
      model: request.deployment.modelId,
      startedAt: STARTED_AT,
      completedAt: COMPLETED_AT,
    };
  }

  private timeoutFailure(request: LlmRequest): LlmProviderError {
    return {
      code: 'timeout',
      safeMessage: 'The deterministic base-1 deployment timed out.',
      provider: request.deployment.providerId,
      model: request.deployment.modelId,
      recoverable: true,
    };
  }
}

const pool = createIntegrationPool();
await assertModelFuseSchema(pool);

const conversationRepository = new ConversationRepository(pool);
const contextRepository = new ContextRepository(pool);
const turnRepository = new TurnRepository(pool);
const publisher = new TurnEventPublisher();
const providerRegistry: ProviderRegistry = {
  openai: new ScenarioLlmProvider('openai'),
  google: new ScenarioLlmProvider('google'),
  openrouter: new ScenarioLlmProvider('openrouter'),
};

function providersFor(scenario: CatalogScenario): ProviderRegistry {
  const providers: Partial<Record<ProviderId, LlmProvider>> = {};
  for (const providerId of catalogScenarioProviders[scenario]) {
    const provider = providerRegistry[providerId];
    if (provider) providers[providerId] = provider;
  }
  return providers;
}

const modelCatalogServices: Readonly<Record<CatalogScenario, ModelCatalogService>> = {
  full: new ModelCatalogService(deploymentDefinitions, providersFor('full')),
  'without-openai': new ModelCatalogService(
    deploymentDefinitions,
    providersFor('without-openai')
  ),
  'without-openrouter': new ModelCatalogService(
    deploymentDefinitions,
    providersFor('without-openrouter')
  ),
};

class RequestModelCatalogService extends ModelCatalogService {
  constructor() {
    super([], {});
  }

  override listAvailableDeployments() {
    return this.current().listAvailableDeployments();
  }

  override getAvailableDeployment(deploymentId: string) {
    return this.current().getAvailableDeployment(deploymentId);
  }

  override resolveExplicitAssignment(assignment: Parameters<ModelCatalogService['resolveExplicitAssignment']>[0]) {
    return this.current().resolveExplicitAssignment(assignment);
  }

  override resolveDefaultAssignment() {
    return this.current().resolveDefaultAssignment();
  }

  private current(): ModelCatalogService {
    return modelCatalogServices[requestCatalogScenario.getStore() ?? 'full'];
  }
}

const modelCatalogService = new RequestModelCatalogService();
const orchestrator = new TurnOrchestrator({
  turnRepository,
  providerRegistry,
  publisher,
  contextBuilder: new ContextBuilder({ contextRepository, maxTurns: 10, thresholdRatio: 0.8 }),
});
const conversationService = new ConversationService({
  conversationRepository,
  turnRepository,
  orchestrator,
  modelCatalogService,
});
const app = createApp({
  conversationService,
  turnEventPublisher: publisher,
  providerRegistry,
  modelCatalogService,
});

function catalogScenarioFromAuthorization(authorization: string | undefined): CatalogScenario {
  const prefix = `Bearer modelfuse-e2e:${runId}:`;
  if (!authorization?.startsWith(prefix)) return 'full';
  const scenario = authorization.slice(prefix.length);
  return scenario in catalogScenarioProviders ? (scenario as CatalogScenario) : 'full';
}

const server = createServer(async (request, response) => {
  const url = new URL(request.url ?? '/', `http://${HOST}:${PORT}`);

  if (request.method === 'GET' && url.pathname === '/__e2e/health') {
    response.statusCode = 204;
    response.end();
    return;
  }

  if (request.method === 'POST' && url.pathname === '/__e2e/shutdown') {
    if (request.headers['x-modelfuse-e2e-run-id'] !== runId) {
      response.statusCode = 403;
      response.end();
      return;
    }

    response.statusCode = 204;
    response.once('finish', () => {
      setImmediate(() => exitAfterShutdown());
    });
    response.end();
    return;
  }

  if (request.method === 'POST' && url.pathname === '/__e2e/release-continuation') {
    const prompt = url.searchParams.get('prompt');
    if (!prompt || !prompt.includes(`[run:${runId}:`)) {
      response.statusCode = 400;
      response.end();
      return;
    }

    continuationGate(prompt).release();
    response.statusCode = 204;
    response.end();
    return;
  }

  const cleanupMatch = /^\/__e2e\/conversations\/([^/]+)$/.exec(url.pathname);
  if (request.method === 'DELETE' && cleanupMatch) {
    const conversationId = cleanupMatch[1];
    if (!UUID_PATTERN.test(conversationId)) {
      response.statusCode = 400;
      response.end();
      return;
    }

    try {
      const deleted = await pool.query(
        `DELETE FROM conversations c
          WHERE c.id = $1
            AND EXISTS (
              SELECT 1 FROM turns t
               WHERE t.conversation_id = c.id
                 AND t.ordinal = 1
                 AND position($2 in t.user_content) > 0
            )
        RETURNING c.id`,
        [conversationId, `[run:${runId}:`]
      );
      response.statusCode = deleted.rowCount === 1 ? 204 : 404;
      response.end();
    } catch {
      response.statusCode = 500;
      response.end();
    }
    return;
  }

  requestCatalogScenario.run(
    catalogScenarioFromAuthorization(request.headers.authorization),
    () => app(request, response)
  );
});

await new Promise<void>((resolve, reject) => {
  server.once('error', reject);
  server.listen(PORT, HOST, () => {
    server.off('error', reject);
    resolve();
  });
});

console.log(`ModelFuse E2E backend ready on http://${HOST}:${PORT}`);

let closing = false;
async function shutdown(): Promise<void> {
  if (closing) return;
  closing = true;
  await new Promise<void>(resolve => {
    server.close(() => resolve());
    server.closeAllConnections();
  });
  await pool.end();
}

function exitAfterShutdown(): void {
  void shutdown().then(
    () => process.exit(0),
    error => {
      console.error(
        `ModelFuse E2E backend shutdown failed: ${error instanceof Error ? error.message : 'unknown error'}`
      );
      process.exit(1);
    }
  );
}

for (const signal of ['SIGINT', 'SIGTERM'] as const) {
  process.once(signal, () => {
    exitAfterShutdown();
  });
}
