import { createServer } from 'node:http';
import process from 'node:process';

import { createApp } from '../../../backend/src/app.js';
import { ConversationRepository } from '../../../backend/src/infrastructure/postgres/repositories/conversationRepository.js';
import { TurnRepository } from '../../../backend/src/infrastructure/postgres/repositories/turnRepository.js';
import { ConversationService } from '../../../backend/src/services/conversations/ConversationService.js';
import { TurnEventPublisher } from '../../../backend/src/services/conversations/turnEventPublisher.js';
import { TurnOrchestrator } from '../../../backend/src/services/conversations/TurnOrchestrator.js';
import {
  assertModelFuseSchema,
  createIntegrationPool,
} from '../../../backend/src/test/integration/testDatabase.js';
import type { ResponseSlot } from '../../../backend/src/types/conversations.js';
import type {
  LlmProvider,
  LlmProviderError,
  LlmRequest,
  LlmResult,
} from '../../../backend/src/types/llm.js';
import { E2E_FRONTEND_ORIGIN, fakeModelResponses, fakeModelScenarios } from './scenarios.js';

const PORT = 3001;
const HOST = '127.0.0.1';
const STARTED_AT = '2026-01-02T03:04:05.000Z';
const COMPLETED_AT = '2026-01-02T03:04:06.000Z';
const RUN_ID_PATTERN = /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const UUID_PATTERN = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;

const runId = process.env.MODELFUSE_E2E_RUN_ID;
if (!runId || !RUN_ID_PATTERN.test(runId)) {
  throw new Error('MODELFUSE_E2E_RUN_ID must be a UUID generated by Playwright');
}

process.env.NODE_ENV = 'test';
process.env.FRONTEND_URL_LOCALHOST = E2E_FRONTEND_ORIGIN;

const responseContent = Object.fromEntries(
  fakeModelResponses.map(response => [response.slot, response.content])
) as Record<ResponseSlot, string>;

class ScenarioLlmProvider implements LlmProvider {
  readonly provider: string;
  readonly model: string;
  readonly context = {
    limitTokens: 10_000,
    measureInputTokens: () => ({ kind: 'exact' as const, tokens: 1 }),
  };

  private readonly callsByPrompt = new Map<string, number>();

  constructor(readonly slot: ResponseSlot) {
    this.provider = `${slot}-e2e-fake`;
    this.model = `${slot}-e2e-model`;
  }

  async generate(request: LlmRequest): Promise<LlmResult> {
    const prompt = request.messages.at(-1)?.content ?? '';

    if (this.slot === 'openai' && prompt.includes(fakeModelScenarios.retry.marker)) {
      const attempt = (this.callsByPrompt.get(prompt) ?? 0) + 1;
      this.callsByPrompt.set(prompt, attempt);
      if (attempt === 1) throw this.timeoutFailure();
      return this.result(fakeModelScenarios.retry.recoveredOpenAiContent);
    }

    if (this.slot === 'openai' && prompt.includes(fakeModelScenarios.continueWithout.marker)) {
      throw this.timeoutFailure();
    }

    if (this.slot === 'qwen' && prompt.includes(fakeModelScenarios.retry.marker)) {
      const hasRecoveredOpenAi = request.messages.some(message =>
        message.content.includes(`openai:\n${fakeModelScenarios.retry.recoveredOpenAiContent}`)
      );
      return this.result(
        hasRecoveredOpenAi
          ? fakeModelScenarios.retry.reconsolidatedQwenContent
          : fakeModelScenarios.retry.initialQwenContent
      );
    }

    return this.result(responseContent[this.slot]);
  }

  private result(content: string): LlmResult {
    return {
      content,
      provider: this.provider,
      model: this.model,
      startedAt: STARTED_AT,
      completedAt: COMPLETED_AT,
    };
  }

  private timeoutFailure(): LlmProviderError {
    return {
      code: 'timeout',
      safeMessage: 'The deterministic OpenAI provider timed out.',
      provider: this.provider,
      model: this.model,
      recoverable: true,
    };
  }
}

const pool = createIntegrationPool();
await assertModelFuseSchema(pool);

const conversationRepository = new ConversationRepository(pool);
const turnRepository = new TurnRepository(pool);
const publisher = new TurnEventPublisher();
const providerRegistry: Record<ResponseSlot, LlmProvider> = {
  openai: new ScenarioLlmProvider('openai'),
  google: new ScenarioLlmProvider('google'),
  minimax: new ScenarioLlmProvider('minimax'),
  qwen: new ScenarioLlmProvider('qwen'),
};
const orchestrator = new TurnOrchestrator({
  turnRepository,
  providerRegistry,
  publisher,
});
const conversationService = new ConversationService({
  conversationRepository,
  turnRepository,
  orchestrator,
});
const app = createApp({ conversationService, turnEventPublisher: publisher });

const server = createServer(async (request, response) => {
  const url = new URL(request.url ?? '/', `http://${HOST}:${PORT}`);

  if (request.method === 'GET' && url.pathname === '/__e2e/health') {
    response.statusCode = 204;
    response.end();
    return;
  }

  const cleanupMatch = /^\/__e2e\/conversations\/([^/]+)$/.exec(url.pathname);
  if (request.method === 'DELETE' && cleanupMatch) {
    const conversationId = cleanupMatch[1];
    if (!UUID_PATTERN.test(conversationId)) {
      response.statusCode = 400;
      response.end();
      return;
    }

    try {
      const deleted = await pool.query(
        `DELETE FROM conversations c
          WHERE c.id = $1
            AND EXISTS (
              SELECT 1 FROM turns t
               WHERE t.conversation_id = c.id
                 AND t.ordinal = 1
                 AND position($2 in t.user_content) > 0
            )
        RETURNING c.id`,
        [conversationId, `[run:${runId}:`]
      );
      response.statusCode = deleted.rowCount === 1 ? 204 : 404;
      response.end();
    } catch {
      response.statusCode = 500;
      response.end();
    }
    return;
  }

  app(request, response);
});

await new Promise<void>((resolve, reject) => {
  server.once('error', reject);
  server.listen(PORT, HOST, () => {
    server.off('error', reject);
    resolve();
  });
});

console.log(`ModelFuse E2E backend ready on http://${HOST}:${PORT}`);

let closing = false;
async function shutdown(): Promise<void> {
  if (closing) return;
  closing = true;
  await new Promise<void>(resolve => {
    server.close(() => resolve());
    server.closeAllConnections();
  });
  await pool.end();
}

for (const signal of ['SIGINT', 'SIGTERM'] as const) {
  process.once(signal, () => {
    void shutdown().then(() => {
      process.exitCode = 0;
    });
  });
}
