import path from 'node:path';
import process from 'node:process';

import { createServer, type Plugin, type ViteDevServer } from 'vite';

import { E2E_FRONTEND_ORIGIN } from './scenarios.js';

const RUN_ID_PATTERN =
  /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const runId = process.env.MODELFUSE_E2E_RUN_ID;
if (!runId || !RUN_ID_PATTERN.test(runId)) {
  throw new Error('MODELFUSE_E2E_RUN_ID must be a UUID generated by Playwright');
}

const origin = new URL(E2E_FRONTEND_ORIGIN);
let viteServer: ViteDevServer | undefined;
let closing = false;

function exitAfterShutdown(): void {
  if (closing) return;
  closing = true;
  void viteServer?.close().then(
    () => process.exit(0),
    error => {
      console.error(
        `ModelFuse E2E frontend shutdown failed: ${error instanceof Error ? error.message : 'unknown error'}`
      );
      process.exit(1);
    }
  );
}

const shutdownPlugin: Plugin = {
  name: 'modelfuse-e2e-shutdown',
  configureServer(server) {
    server.middlewares.use((request, response, next) => {
      const url = new URL(request.url ?? '/', origin);
      if (request.method !== 'POST' || url.pathname !== '/__e2e/shutdown') {
        next();
        return;
      }

      if (request.headers['x-modelfuse-e2e-run-id'] !== runId) {
        response.statusCode = 403;
        response.end();
        return;
      }

      response.statusCode = 204;
      response.once('finish', () => {
        setImmediate(() => exitAfterShutdown());
      });
      response.end();
    });
  },
};

viteServer = await createServer({
  root: path.resolve(import.meta.dirname, '../..'),
  plugins: [shutdownPlugin],
  server: {
    host: origin.hostname,
    port: Number(origin.port),
    strictPort: true,
  },
});
await viteServer.listen();
viteServer.printUrls();

for (const signal of ['SIGINT', 'SIGTERM'] as const) {
  process.once(signal, exitAfterShutdown);
}
