import { describe, expect, it } from 'vitest';

import { DEPLOYMENT_CATALOG } from '../deploymentCatalog.js';

describe('DEPLOYMENT_CATALOG', () => {
  it('contains exactly the ten normative deployment definitions', () => {
    expect(DEPLOYMENT_CATALOG).toHaveLength(10);
    expect(DEPLOYMENT_CATALOG).toEqual([
      {
        deploymentId: 'openrouter-minimax-m3',
        displayName: 'MiniMax M3',
        providerId: 'openrouter',
        modelId: 'minimax/minimax-m3',
        contextLimitTokens: 524288,
        inputModalities: ['text', 'image', 'video'],
        outputModalities: ['text'],
        credentialEnv: 'OPENROUTER_API_KEY',
      },
      {
        deploymentId: 'openrouter-minimax-m2.7',
        displayName: 'MiniMax M2.7',
        providerId: 'openrouter',
        modelId: 'minimax/minimax-m2.7',
        contextLimitTokens: 204800,
        inputModalities: ['text'],
        outputModalities: ['text'],
        credentialEnv: 'OPENROUTER_API_KEY',
      },
      {
        deploymentId: 'openrouter-qwen-3.8-max',
        displayName: 'Qwen 3.8 Max',
        providerId: 'openrouter',
        modelId: 'qwen/qwen3.8-max',
        contextLimitTokens: 1000000,
        inputModalities: ['text', 'image', 'video'],
        outputModalities: ['text'],
        credentialEnv: 'OPENROUTER_API_KEY',
      },
      {
        deploymentId: 'openrouter-kimi-k3',
        displayName: 'Kimi K3',
        providerId: 'openrouter',
        modelId: 'moonshotai/kimi-k3',
        contextLimitTokens: 1048576,
        inputModalities: ['text', 'image', 'video'],
        outputModalities: ['text'],
        credentialEnv: 'OPENROUTER_API_KEY',
      },
      {
        deploymentId: 'openrouter-glm-5.2',
        displayName: 'GLM 5.2',
        providerId: 'openrouter',
        modelId: 'z-ai/glm-5.2',
        contextLimitTokens: 1048576,
        inputModalities: ['text'],
        outputModalities: ['text'],
        credentialEnv: 'OPENROUTER_API_KEY',
      },
      {
        deploymentId: 'openrouter-deepseek-v4-flash-0731',
        displayName: 'DeepSeek V4 Flash 0731',
        providerId: 'openrouter',
        modelId: 'deepseek/deepseek-v4-flash-0731',
        contextLimitTokens: 1048576,
        inputModalities: ['text'],
        outputModalities: ['text'],
        credentialEnv: 'OPENROUTER_API_KEY',
      },
      {
        deploymentId: 'gemini-3.7-flash',
        displayName: 'Gemini 3.7 Flash',
        providerId: 'google',
        modelId: 'gemini-3.7-flash',
        contextLimitTokens: 1048576,
        inputModalities: ['text', 'image', 'video', 'audio', 'pdf'],
        outputModalities: ['text'],
        credentialEnv: 'GOOGLE_API_KEY',
      },
      {
        deploymentId: 'openai-5.6-sol',
        displayName: 'GPT-5.6 Sol',
        providerId: 'openai',
        modelId: 'gpt-5.6-sol',
        contextLimitTokens: 1050000,
        inputModalities: ['text', 'image'],
        outputModalities: ['text'],
        credentialEnv: 'OPENAI_API_KEY',
      },
      {
        deploymentId: 'openai-5.6-terra',
        displayName: 'GPT-5.6 Terra',
        providerId: 'openai',
        modelId: 'gpt-5.6-terra',
        contextLimitTokens: 1050000,
        inputModalities: ['text', 'image'],
        outputModalities: ['text'],
        credentialEnv: 'OPENAI_API_KEY',
      },
      {
        deploymentId: 'openai-5.6-luna',
        displayName: 'GPT-5.6 Luna',
        providerId: 'openai',
        modelId: 'gpt-5.6-luna',
        contextLimitTokens: 1050000,
        inputModalities: ['text', 'image'],
        outputModalities: ['text'],
        credentialEnv: 'OPENAI_API_KEY',
      },
    ]);
  });
});
